name: Build Go binaries

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make release
        uses: varrcan/build-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
